include: package:lints/recommended.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_single_quotes: true 
    sort_constructors_first: true
    avoid_unused_constructor_parameters: true
    empty_catches: true
    file_names: true
    # public_member_api_docs: true
    slash_for_doc_comments: true
    unawaited_futures: true
    unnecessary_late: true
    unnecessary_getters_setters: true
    require_trailing_commas: true
    always_use_package_imports: true

analyzer:
  exclude:
    .bin/**
    lib/generated/**
    lib/**.g.dart
    lib/**.freezed.dart
