name: pluma
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/cosmopool/pluma

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
